### ISSUE TITLE
Install Request: RStudio IDE version on Myriad for Economics

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#418]
requested by Lars.

**Comment by balston** [comment]
RStudio IDE is available as either a binary installer archive or source code from here:
```
https://rstudio.com/products/rstudio/download/#download
```
I suggest we install the binary version if it works. there is a version for RedHat 7 in either RPM or gzipped tar:
```
https://download1.rstudio.org/desktop/centos7/x86_64/rstudio-1.4.1106-x86_64-fedora.tar.gz
```

**Comment by balston** [comment]
I'm downloading a copy of the gzipped tar archive to see what is needed for installation. It requires a version of R that's at least version 3.0.1 - none of the versions we have on Myriad are this old so no problem there.

**Comment by balston** [comment]
It looks like the archive should just untar in place and then it should work with a suitable module file. I'm going to do a build script for this next and then work out a suitable module file.

**Comment by balston** [comment]
Build script for the binary version done. Running as _ccspapp_:
```
cd /shared/ucl/apps/build_scripts
./RStudio-IDE-1.4.1106_install
```

**Comment by balston** [comment]
Of course my first attempt at a new build script often fails! In this case I forgot an important mkdir. Fixing and running again.

**Comment by balston** [comment]
Install appears to have completed OK. I'm now doing a module file but first I need to check dependencies apart from R itself of course. Unfortunately neither of the Read Me files included with the binary archive list them. All they do is point to documentation included with the source code so I'm now downloading the source to have a look.

**Comment by balston** [comment]
Dependencies as listed are:
- R 3.0.1
- CMake 3.4.3 or newer
- Boost 1.69
- Qt 5.12.8 [Required only for Desktop]
- patchelf 0.9 [Required only for Desktop]

All are versions of R are more recent than this one so no problem there. 

I assume cmake is only used when building from source but we have it in the default modules anyway.

We don't currently have Qt 5.12.8 - we only have 5.12.1 but it looks like the binary install includes the necessary Qt libraries so OK there.

We don't have a recent enough version of Boost (our latest is boost/1_63_0/gnu-4.9.2) so will need to build 1.69.

We don't have patchelf so will need to build this as well.

**Comment by tkoskela** [comment]
- [x] R 3.0.1
- [x] CMake 3.4.3 or newer
- [ ] Boost 1.69
- [ ] Qt 5.12.8 [Required only for Desktop]
- [ ] patchelf 0.9 [Required only for Desktop]

**Comment by tkoskela** [comment]
> We don't have a recent enough version of Boost (our latest is boost/1_63_0/gnu-4.9.2) so will need to build 1.69.

I can see we now have `boost/1.75.0/gnu-4.9.2` installed (by Ian 4 months ago) so that should be fine

**Comment by tkoskela** [comment]
- Qt builds successfully (after a long time) 
- patchelf builds but fails some tests that try to link `libimf.so` unsuccessfully. `libimf.so` is in the intel compiler module under `linux/lib/intel64/` but if I point to that in configure, I get more dynamic linking errors. The module does not seem to add it to `LD_LIBRARY_PATH` by default. Am I missing something?

**Comment by heatherkellyucl** [comment]
What modules do you have loaded for these? R uses the gnu compiler so everything here ought to be using that toolchain and not Intel.

**Comment by tkoskela** [comment]
Ohh, that could be a problem

**Comment by tkoskela** [comment]
The prebuilt Rstudio binary fails to start because it's failing to link `libxkbcommon-x11.so`. It seems to look in it's private `lib` directory and in `/lib64`. We don't have the library in `/lib64`, but it seems available e.g. https://pkgs.org/download/libxkbcommon-x11. Where's the best place to put it?

**Comment by balston** [comment]
I think I built a version of libxkb for a previous version of Qt. Have a look at:
```
/shared/ucl/apps/build_scripts/qt-support-xkbcommon-0.8.4_install
```

**Comment by tkoskela** [comment]
Although I'm starting to wonder why they want to use an IDE over x11... Unless it can be run with a local client?

**Comment by heatherkellyucl** [comment]
There's also the other bits and pieces of X11 we've needed to add that are in the xorg-utils module and the buildscript is xorg-utils-X11R7.7_install (is designed so you can add another on at the bottom and only build specific segments with the BUILD_XXX=yes when you run it).

Brian's is probably more relevant here though!

**Comment by tkoskela** [comment]
I pointed it to link to my private build directory and the `rstudio` app starts, however it's unhappy with the version of OpenGL. 
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
[52715:53258:0812/151749.514178:ERROR:gl_context_glx.cc(232)] Couldn't make context current with X drawable.
[52715:53258:0812/151749.514535:ERROR:gpu_info_collector.cc(68)] gl::GLContext::MakeCurrent() failed
[52715:53258:0812/151749.514567:ERROR:gpu_info_collector.cc(186)] Could not create context for info collection.
Unrecognized OpenGL version
Unrecognized OpenGL version
QQuickWidget: Failed to make context current
QQuickWidget::resizeEvent() no OpenGL context
QQuickWidget: Failed to make context current
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version
Unrecognized OpenGL version
qt.qpa.backingstore: composeAndFlush: makeCurrent() failed
qt.qpa.backingstore: composeAndFlush: makeCurrent() failed
qt.qpa.backingstore: composeAndFlush: makeCurrent() failed
QQuickWidget: Attempted to render scene with no context
```
The only OpenGL library I can see it linking to is one it provides itself so I'm a bit confused.
```
(base) [cceaosk@login13 bin]$ ldd rstudio | grep -i opengl
	libQt5OpenGL.so.5 => /lustre/home/cceaosk/my_module_installs/Rstudio/rstudio-1.4.1106/bin/./../lib/libQt5OpenGL.so.5 (0x00007f077800c000)
(base) [cceaosk@login13 bin]$ ldd rstudio | grep -i gl
	libQt5OpenGL.so.5 => /lustre/home/cceaosk/my_module_installs/Rstudio/rstudio-1.4.1106/bin/./../lib/libQt5OpenGL.so.5 (0x00007f19e4c4e000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f19d6007000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f19d26da000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f19d1b3b000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f19d1885000)
```

**Comment by heatherkellyucl** [comment]
For the last-but-one message, looks like qt 5.12.1 needs installing on Myriad - it is installed on Young, for example.

**Comment by balston** [comment]
I think I was building that version of Qt for some Young users who needed to use a package called Xatalopt so it never got installed elsewhere.

**Comment by tkoskela** [comment]
> You might need to load a mesa module for the second thing? (This is just a guess).

Woo, this worked! Thanks Heather

> I think I was building that version of Qt for some Young users who needed to use a package called Xatalopt so it never got installed elsewhere.

Ah, and the module environment is the same on all machines? Makes sense.

As far as I can tell it's now running without any errors. The GUI is very slow over X so I can't do much to test it. I'm going on leave after today so I don't think I'll have time to run the Qt install, but I'll leave my notes here.

**Comment by tkoskela** [comment]
## TODO to make module

- Extract prebuilt RStudio binaries with `/shared/ucl/apps/build_scripts/RStudio-IDE-1.4.1106_install`
- Install `libxkbcommon-x11.so` with `/shared/ucl/apps/build_scripts/qt-support-xkbcommon-0.8.4_install` and add to linker path
- Require `postgresql/9.5.3/gnu-4.9.2` + dependencies
- Require `r/3.6.0-openblas/gnu-4.9.2` + dependencies
- Require `mesa/6.5/gnu-4.9.2`

**Comment by heatherkellyucl** [comment]
I will run the qt install on Myriad (and make sure it is everywhere).

**Comment by tkoskela** [comment]
This is now done. It runs but it's very slow for me and I have some doubts about how useful it will be. If anyone wants to try it out, `/home/cceaosk/scripts/rstudio_ide_startup.sh` loads the required modules.

There is an RStudio in the [data safe haven desktop](https://www.ucl.ac.uk/isd/services/file-storage-sharing/data-safe-haven/software-and-services) with access to the Myriad filesystem that might be more suitable for Lars.
