### ISSUE TITLE
Resolve various complex and annoying issues with machine learning toolkits

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#472]
This issue contains a bunch of things Owain should so when he has some spare time.

- [x] - Install  new tensorflow #326 
- [x] - Fix Tensorflow accidentally installed onto Python 3.8.6 on Myriad 
- [x] - Fix pytorch/pip package mess #460

**Comment by owainkenwayucl** [comment]
Owain should also:

- [ ] - Finish the  Python 3.9 build #385 
- [ ] - document the process and hand it off to someone

**Comment by owainkenwayucl** [comment]
To remove tensorflow:

```
pip3 uninstall absl-py astunparse cachetools certifi charset-normalizer flatbuffers gast google-auth google-auth-oauthlib google-pasta grpcio h5py idna importlib-metadata keras Keras-Preprocessing libclang Markdown oauthlib opt-einsum protobuf pyasn1 pyasn1-modules requests requests-oauthlib rsa tensorboard tensorboard-data-server tensorboard-plugin-wit tensorflow tensorflow-estimator tensorflow-io-gcs-filesystem termcolor typing-extensions urllib3 Werkzeug wheel wrapt zipp
```

**Comment by owainkenwayucl** [comment]
It looks like tensorflow wheels now work on RHEL 7 which should make installing an up to date tensorflow easier.

**Comment by owainkenwayucl** [comment]
Tensorflow 2.8.0 installed.

**Comment by owainkenwayucl** [comment]
I think given the plan to move to spack, this long running issue can now be closed as all that was left was documenting the old process.
